In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [12]:
X_train

      age     bmi  children  sex_male  smoker_yes
1163   18  28.215         0         0           0
196    39  32.800         0         0           0
438    52  46.750         5         0           0
183    44  26.410         0         0           0
1298   33  27.455         2         1           0
...   ...     ...       ...       ...         ...
763    27  26.030         0         1           0
835    42  35.970         2         1           0
1216   40  25.080         0         1           0
559    19  35.530         0         1           0
684    33  18.500         1         0           0

[936 rows x 5 columns]

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = { 'kernel': ['rbf', 'poly', 'sigmoid', 'linear'], 'C': [10, 100, 1000, 2000, 3000], 'gamma': ['auto', 'scale'] }
grid=GridSearchCV(SVR(),param_grid,refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train,Y_train)

C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fold_sizes = np.full(n_splits, n_samples // n_splits, dtype=np.int)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:102: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_mask = np.zeros(_num_samples(X), dtype=np.bool)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.

Fitting 3 folds for each of 40 candidates, totalling 120 fits

[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    1.7s finished
C:\Anaconda\lib\site-packages\sklearn\model_selection\_search.py:794: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int)
C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='auto_deprecated', kernel='rbf',
                           max_iter=-1, shrinking=True, tol=0.001,
                           verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [15]:
re=grid.cv_results_
print ("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.014758,0.001834,0.000477,0.000674,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.001622,-0.097907,-0.088465,-0.062665,0.043335,36
1,0.010664,0.000000,0.000000,0.000000,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.045578,-0.050102,-0.039371,-0.014632,0.042800,32
2,0.020841,0.007368,0.000000,0.000000,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.043747,-0.054054,-0.044185,-0.018164,0.043962,34
3,0.017026,0.003582,0.000667,0.000943,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.379453,0.263743,0.270498,0.304565,0.053026,27
4,0.007069,0.006777,0.006802,0.006564,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.001551,-0.097995,-0.088478,-0.062675,0.043395,37
5,0.012306,0.003776,0.003747,0.003546,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.044344,-0.048766,-0.039184,-0.014535,0.041817,31
6,0.018507,0.002188,0.007874,0.005541,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.043460,-0.053762,-0.044135,-0.018146,0.043738,33
7,0.020029,0.003626,0.001911,0.001355,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.379453,0.263743,0.270498,0.304565,0.053026,27
8,0.009313,0.010376,0.010449,0.007388,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.280420,0.159180,0.155842,0.198481,0.057956,29
9,0.015673,0.000000,0.000000,0.000000,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.519516,0.445794,0.421048,0.462119,0.041824,22
10,0.017179,0.007388,0.000000,0.000000,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.497513,0.425077,0.420930,0.447840,0.035165,24
11,0.011954,0.000000,0.005515,0.007799,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.600824,0.573673,0.559680,0.578059,0.017081,19
12,0.013484,0.002164,0.010724,0.007592,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.280931,0.158637,0.155756,0.198441,0.058341,30
13,0.016544,0.000000,0.000000,0.000000,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.514963,0.450772,0.421861,0.462532,0.038908,21
14,0.022992,0.006664,0.008736,0.006872,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.495602,0.426898,0.421539,0.448013,0.033721,23
15,0.006421,0.009080,0.011962,0.007127,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.600824,0.573673,0.559680,0.578059,0.017081,19
16,0.022571,0.000000,0.000000,0.000000,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.713543,0.671971,0.640038,0.675184,0.030094,11
17,0.022571,0.000000,0.007125,0.005038,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.797601,0.795391,0.764729,0.785907,0.015002,8
18,0.029695,0.005038,0.003562,0.005038,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.405221,0.336416,0.349444,0.363694,0.029842,25
19,0.014995,0.000817,0.000000,0.000000,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.663978,0.673763,0.637674,0.658471,0.015239,13
20,0.011123,0.000617,0.006117,0.008651,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.713824,0.671576,0.639937,0.675112,0.030267,12
21,0.036684,0.009538,0.004880,0.003930,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.797154,0.795738,0.764963,0.785952,0.014853,7
22,0.022545,0.000137,0.000097,0.000137,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.385746,0.319360,0.346897,0.350668,0.027233,26
23,0.022642,0.000000,0.000000,0.000000,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.663978,0.673763,0.637674,0.658471,0.015239,13
24,0.022642,0.000000,0.013027,0.001247,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.794232,0.780655,0.746425,0.773770,0.020115,9
25,0.040990,0.010639,0.001432,0.001229,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.822616,0.813670,0.779845,0.805377,0.018419,3
26,0.018412,0.001279,0.005213,0.005832,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.192402,-0.162949,-0.041406,-0.132252,0.065354,38
27,0.022523,0.005570,0.004452,0.004950,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.710113,0.621857,0.634263,0.655411,0.039010,15
28,0.017737,0.001544,0.008570,0.006074,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.794443,0.780342,0.746377,0.773721,0.020174,10
29,0.037202,0.006673,0.001334,0.001248,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.821856,0.813718,0.779857,0.805144,0.018187,4
30,0.021187,0.004117,0.003100,0.002211,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.038754,-0.046722,-0.043343,-0.042940,0.003266,35
31,0.022530,0.005082,0.000667,0.000943,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.710113,0.621857,0.634263,0.655411,0.039010,15
32,0.024733,0.006091,0.003787,0.005356,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.805659,0.800880,0.768195,0.791578,0.016649,6
33,0.042797,0.008194,0.007257,0.005147,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.824951,0.814057,0.783380,0.807463,0.017600,1
34,0.017070,0.000612,0.004469,0.006320,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.935044,-0.652358,-0.912173,-0.833192,0.128209,39
35,0.033744,0.012277,0.000333,0.000471,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.710020,0.621851,0.632748,0.654873,0.039248,17
36,0.022652,0.007533,0.003452,0.004881,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.805853,0.800723,0.768176,0.791584,0.016684,5
37,0.033707,0.009335,0.001333,0.000943,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.825027,0.813966,0.783395,0.807463,0.017607,2
38,0.021466,0.005430,0.006323,0.004350,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.924846,-1.126127,-0.940265,-0.997079,0.091467,40
39,0.023151,0.009291,0.000429,0.000606,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.710020,0.621851,0.632748,0.654873,0.039248,17

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:43
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [19]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]]) 
print("Future Prediction: {}".format(Future_Prediction))

Future Prediction: [2291197.32937632]